export { characterAwareFilter } from './character-filter'
export type { FilteredResult, SearchResult } from './character-filter'
export { intelligentWebSearch } from './intelligent-search'
export { intentAnalyzer } from './intent-analyzer'
export type { IntentAnalysis } from './intent-analyzer'
export type { IntegratedKnowledge } from './knowledge-integrator'

export { queryBuilder } from './query-builder'
export type { QueryStrategy } from './query-builder'
export { digestSearchResults } from './response-digester'
export type { CharacterOpinion, DigestedInformation, ExpressionSuggestions, MainFinding } from './response-digester'
export { webSearch } from './web-search'
